<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup Label="Add SCSS files to dotnet watch">
    <Watch Include="**\*.scss" />
    <None Update="**\*.css" watch="false" />
  </ItemGroup>

  <ItemGroup Label="Compile SCSS files">
    <ComponentScssFiles
      Include="**/*/*.scss;**/*.scss"
      Exclude="node_modules/**;wwwroot/**;Styles/**" />
  </ItemGroup>


</Project>
